# Generated by Django 3.2.10 on 2024-02-26 04:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grammar_correct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarcheck',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='grammarcheck',
            name='user1',
            field=models.IntegerField(default=0),
        ),
    ]
