# Generated by Django 3.2.10 on 2024-02-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_to_summary', '0003_auto_20240226_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='user1',
            field=models.IntegerField(default=0),
        ),
    ]
